production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: /solr-4.10.2/default #production #ollection1 #production
#    solr_home: solr
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    
