require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CalentriesController do

  # This should return the minimal set of attributes required to create a valid
  # Calentry. As you add validations to Calentry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "start" => "2013-08-05 21:17:10" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CalentriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all calentries as @calentries" do
      calentry = Calentry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:calentries).should eq([calentry])
    end
  end

  describe "GET show" do
    it "assigns the requested calentry as @calentry" do
      calentry = Calentry.create! valid_attributes
      get :show, {:id => calentry.to_param}, valid_session
      assigns(:calentry).should eq(calentry)
    end
  end

  describe "GET new" do
    it "assigns a new calentry as @calentry" do
      get :new, {}, valid_session
      assigns(:calentry).should be_a_new(Calentry)
    end
  end

  describe "GET edit" do
    it "assigns the requested calentry as @calentry" do
      calentry = Calentry.create! valid_attributes
      get :edit, {:id => calentry.to_param}, valid_session
      assigns(:calentry).should eq(calentry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Calentry" do
        expect {
          post :create, {:calentry => valid_attributes}, valid_session
        }.to change(Calentry, :count).by(1)
      end

      it "assigns a newly created calentry as @calentry" do
        post :create, {:calentry => valid_attributes}, valid_session
        assigns(:calentry).should be_a(Calentry)
        assigns(:calentry).should be_persisted
      end

      it "redirects to the created calentry" do
        post :create, {:calentry => valid_attributes}, valid_session
        response.should redirect_to(Calentry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved calentry as @calentry" do
        # Trigger the behavior that occurs when invalid params are submitted
        Calentry.any_instance.stub(:save).and_return(false)
        post :create, {:calentry => { "start" => "invalid value" }}, valid_session
        assigns(:calentry).should be_a_new(Calentry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Calentry.any_instance.stub(:save).and_return(false)
        post :create, {:calentry => { "start" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested calentry" do
        calentry = Calentry.create! valid_attributes
        # Assuming there are no other calentries in the database, this
        # specifies that the Calentry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Calentry.any_instance.should_receive(:update_attributes).with({ "start" => "2013-08-05 21:17:10" })
        put :update, {:id => calentry.to_param, :calentry => { "start" => "2013-08-05 21:17:10" }}, valid_session
      end

      it "assigns the requested calentry as @calentry" do
        calentry = Calentry.create! valid_attributes
        put :update, {:id => calentry.to_param, :calentry => valid_attributes}, valid_session
        assigns(:calentry).should eq(calentry)
      end

      it "redirects to the calentry" do
        calentry = Calentry.create! valid_attributes
        put :update, {:id => calentry.to_param, :calentry => valid_attributes}, valid_session
        response.should redirect_to(calentry)
      end
    end

    describe "with invalid params" do
      it "assigns the calentry as @calentry" do
        calentry = Calentry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Calentry.any_instance.stub(:save).and_return(false)
        put :update, {:id => calentry.to_param, :calentry => { "start" => "invalid value" }}, valid_session
        assigns(:calentry).should eq(calentry)
      end

      it "re-renders the 'edit' template" do
        calentry = Calentry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Calentry.any_instance.stub(:save).and_return(false)
        put :update, {:id => calentry.to_param, :calentry => { "start" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested calentry" do
      calentry = Calentry.create! valid_attributes
      expect {
        delete :destroy, {:id => calentry.to_param}, valid_session
      }.to change(Calentry, :count).by(-1)
    end

    it "redirects to the calentries list" do
      calentry = Calentry.create! valid_attributes
      delete :destroy, {:id => calentry.to_param}, valid_session
      response.should redirect_to(calentries_url)
    end
  end

end
