require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FetmeetingsController do

  # This should return the minimal set of attributes required to create a valid
  # Fetmeeting. As you add validations to Fetmeeting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tnlist" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FetmeetingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fetmeetings as @fetmeetings" do
      fetmeeting = Fetmeeting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fetmeetings).should eq([fetmeeting])
    end
  end

  describe "GET show" do
    it "assigns the requested fetmeeting as @fetmeeting" do
      fetmeeting = Fetmeeting.create! valid_attributes
      get :show, {:id => fetmeeting.to_param}, valid_session
      assigns(:fetmeeting).should eq(fetmeeting)
    end
  end

  describe "GET new" do
    it "assigns a new fetmeeting as @fetmeeting" do
      get :new, {}, valid_session
      assigns(:fetmeeting).should be_a_new(Fetmeeting)
    end
  end

  describe "GET edit" do
    it "assigns the requested fetmeeting as @fetmeeting" do
      fetmeeting = Fetmeeting.create! valid_attributes
      get :edit, {:id => fetmeeting.to_param}, valid_session
      assigns(:fetmeeting).should eq(fetmeeting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fetmeeting" do
        expect {
          post :create, {:fetmeeting => valid_attributes}, valid_session
        }.to change(Fetmeeting, :count).by(1)
      end

      it "assigns a newly created fetmeeting as @fetmeeting" do
        post :create, {:fetmeeting => valid_attributes}, valid_session
        assigns(:fetmeeting).should be_a(Fetmeeting)
        assigns(:fetmeeting).should be_persisted
      end

      it "redirects to the created fetmeeting" do
        post :create, {:fetmeeting => valid_attributes}, valid_session
        response.should redirect_to(Fetmeeting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fetmeeting as @fetmeeting" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fetmeeting.any_instance.stub(:save).and_return(false)
        post :create, {:fetmeeting => { "tnlist" => "invalid value" }}, valid_session
        assigns(:fetmeeting).should be_a_new(Fetmeeting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fetmeeting.any_instance.stub(:save).and_return(false)
        post :create, {:fetmeeting => { "tnlist" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fetmeeting" do
        fetmeeting = Fetmeeting.create! valid_attributes
        # Assuming there are no other fetmeetings in the database, this
        # specifies that the Fetmeeting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fetmeeting.any_instance.should_receive(:update_attributes).with({ "tnlist" => "MyText" })
        put :update, {:id => fetmeeting.to_param, :fetmeeting => { "tnlist" => "MyText" }}, valid_session
      end

      it "assigns the requested fetmeeting as @fetmeeting" do
        fetmeeting = Fetmeeting.create! valid_attributes
        put :update, {:id => fetmeeting.to_param, :fetmeeting => valid_attributes}, valid_session
        assigns(:fetmeeting).should eq(fetmeeting)
      end

      it "redirects to the fetmeeting" do
        fetmeeting = Fetmeeting.create! valid_attributes
        put :update, {:id => fetmeeting.to_param, :fetmeeting => valid_attributes}, valid_session
        response.should redirect_to(fetmeeting)
      end
    end

    describe "with invalid params" do
      it "assigns the fetmeeting as @fetmeeting" do
        fetmeeting = Fetmeeting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fetmeeting.any_instance.stub(:save).and_return(false)
        put :update, {:id => fetmeeting.to_param, :fetmeeting => { "tnlist" => "invalid value" }}, valid_session
        assigns(:fetmeeting).should eq(fetmeeting)
      end

      it "re-renders the 'edit' template" do
        fetmeeting = Fetmeeting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fetmeeting.any_instance.stub(:save).and_return(false)
        put :update, {:id => fetmeeting.to_param, :fetmeeting => { "tnlist" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fetmeeting" do
      fetmeeting = Fetmeeting.create! valid_attributes
      expect {
        delete :destroy, {:id => fetmeeting.to_param}, valid_session
      }.to change(Fetmeeting, :count).by(-1)
    end

    it "redirects to the fetmeetings list" do
      fetmeeting = Fetmeeting.create! valid_attributes
      delete :destroy, {:id => fetmeeting.to_param}, valid_session
      response.should redirect_to(fetmeetings_url)
    end
  end

end
