require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FetmeetingtopsController do

  # This should return the minimal set of attributes required to create a valid
  # Fetmeetingtop. As you add validations to Fetmeetingtop, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FetmeetingtopsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fetmeetingtops as @fetmeetingtops" do
      fetmeetingtop = Fetmeetingtop.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fetmeetingtops).should eq([fetmeetingtop])
    end
  end

  describe "GET show" do
    it "assigns the requested fetmeetingtop as @fetmeetingtop" do
      fetmeetingtop = Fetmeetingtop.create! valid_attributes
      get :show, {:id => fetmeetingtop.to_param}, valid_session
      assigns(:fetmeetingtop).should eq(fetmeetingtop)
    end
  end

  describe "GET new" do
    it "assigns a new fetmeetingtop as @fetmeetingtop" do
      get :new, {}, valid_session
      assigns(:fetmeetingtop).should be_a_new(Fetmeetingtop)
    end
  end

  describe "GET edit" do
    it "assigns the requested fetmeetingtop as @fetmeetingtop" do
      fetmeetingtop = Fetmeetingtop.create! valid_attributes
      get :edit, {:id => fetmeetingtop.to_param}, valid_session
      assigns(:fetmeetingtop).should eq(fetmeetingtop)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fetmeetingtop" do
        expect {
          post :create, {:fetmeetingtop => valid_attributes}, valid_session
        }.to change(Fetmeetingtop, :count).by(1)
      end

      it "assigns a newly created fetmeetingtop as @fetmeetingtop" do
        post :create, {:fetmeetingtop => valid_attributes}, valid_session
        assigns(:fetmeetingtop).should be_a(Fetmeetingtop)
        assigns(:fetmeetingtop).should be_persisted
      end

      it "redirects to the created fetmeetingtop" do
        post :create, {:fetmeetingtop => valid_attributes}, valid_session
        response.should redirect_to(Fetmeetingtop.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fetmeetingtop as @fetmeetingtop" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fetmeetingtop.any_instance.stub(:save).and_return(false)
        post :create, {:fetmeetingtop => { "title" => "invalid value" }}, valid_session
        assigns(:fetmeetingtop).should be_a_new(Fetmeetingtop)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fetmeetingtop.any_instance.stub(:save).and_return(false)
        post :create, {:fetmeetingtop => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fetmeetingtop" do
        fetmeetingtop = Fetmeetingtop.create! valid_attributes
        # Assuming there are no other fetmeetingtops in the database, this
        # specifies that the Fetmeetingtop created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fetmeetingtop.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => fetmeetingtop.to_param, :fetmeetingtop => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested fetmeetingtop as @fetmeetingtop" do
        fetmeetingtop = Fetmeetingtop.create! valid_attributes
        put :update, {:id => fetmeetingtop.to_param, :fetmeetingtop => valid_attributes}, valid_session
        assigns(:fetmeetingtop).should eq(fetmeetingtop)
      end

      it "redirects to the fetmeetingtop" do
        fetmeetingtop = Fetmeetingtop.create! valid_attributes
        put :update, {:id => fetmeetingtop.to_param, :fetmeetingtop => valid_attributes}, valid_session
        response.should redirect_to(fetmeetingtop)
      end
    end

    describe "with invalid params" do
      it "assigns the fetmeetingtop as @fetmeetingtop" do
        fetmeetingtop = Fetmeetingtop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fetmeetingtop.any_instance.stub(:save).and_return(false)
        put :update, {:id => fetmeetingtop.to_param, :fetmeetingtop => { "title" => "invalid value" }}, valid_session
        assigns(:fetmeetingtop).should eq(fetmeetingtop)
      end

      it "re-renders the 'edit' template" do
        fetmeetingtop = Fetmeetingtop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fetmeetingtop.any_instance.stub(:save).and_return(false)
        put :update, {:id => fetmeetingtop.to_param, :fetmeetingtop => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fetmeetingtop" do
      fetmeetingtop = Fetmeetingtop.create! valid_attributes
      expect {
        delete :destroy, {:id => fetmeetingtop.to_param}, valid_session
      }.to change(Fetmeetingtop, :count).by(-1)
    end

    it "redirects to the fetmeetingtops list" do
      fetmeetingtop = Fetmeetingtop.create! valid_attributes
      delete :destroy, {:id => fetmeetingtop.to_param}, valid_session
      response.should redirect_to(fetmeetingtops_url)
    end
  end

end
