require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FragenController do

  # This should return the minimal set of attributes required to create a valid
  # Frage. As you add validations to Frage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FragenController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fragenn as @fragenn" do
      frage = Frage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fragen).should eq([frage])
    end
  end

  describe "GET show" do
    it "assigns the requested frage as @frage" do
      frage = Frage.create! valid_attributes
      get :show, {:id => frage.to_param}, valid_session
      assigns(:frage).should eq(frage)
    end
  end

  describe "GET new" do
    it "assigns a new frage as @frage" do
      get :new, {}, valid_session
      assigns(:frage).should be_a_new(Frage)
    end
  end

  describe "GET edit" do
    it "assigns the requested frage as @frage" do
      frage = Frage.create! valid_attributes
      get :edit, {:id => frage.to_param}, valid_session
      assigns(:frage).should eq(frage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Frage" do
        expect {
          post :create, {:frage => valid_attributes}, valid_session
        }.to change(Frage, :count).by(1)
      end

      it "assigns a newly created frage as @frage" do
        post :create, {:frage => valid_attributes}, valid_session
        assigns(:frage).should be_a(Frage)
        assigns(:frage).should be_persisted
      end

      it "redirects to the created frage" do
        post :create, {:frage => valid_attributes}, valid_session
        response.should redirect_to(Frage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved frage as @frage" do
        # Trigger the behavior that occurs when invalid params are submitted
        Frage.any_instance.stub(:save).and_return(false)
        post :create, {:frage => { "title" => "invalid value" }}, valid_session
        assigns(:frage).should be_a_new(Frage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Frage.any_instance.stub(:save).and_return(false)
        post :create, {:frage => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested frage" do
        frage = Frage.create! valid_attributes
        # Assuming there are no other fragen in the database, this
        # specifies that the Frage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Frage.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => frage.to_param, :frage => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested frage as @frage" do
        frage = Frage.create! valid_attributes
        put :update, {:id => frage.to_param, :frage => valid_attributes}, valid_session
        assigns(:frage).should eq(frage)
      end

      it "redirects to the frage" do
        frage = Frage.create! valid_attributes
        put :update, {:id => frage.to_param, :frage => valid_attributes}, valid_session
        response.should redirect_to(frage)
      end
    end

    describe "with invalid params" do
      it "assigns the frage as @frage" do
        frage = Frage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Frage.any_instance.stub(:save).and_return(false)
        put :update, {:id => frage.to_param, :frage => { "title" => "invalid value" }}, valid_session
        assigns(:frage).should eq(frage)
      end

      it "re-renders the 'edit' template" do
        frage = Frage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Frage.any_instance.stub(:save).and_return(false)
        put :update, {:id => frage.to_param, :frage => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested frage" do
      frage = Frage.create! valid_attributes
      expect {
        delete :destroy, {:id => frage.to_param}, valid_session
      }.to change(Frage, :count).by(-1)
    end

    it "redirects to the fragen list" do
      frage = Frage.create! valid_attributes
      delete :destroy, {:id => frage.to_param}, valid_session
      response.should redirect_to(fragen_url)
    end
  end

end
