require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GremienController do

  # This should return the minimal set of attributes required to create a valid
  # Gremium. As you add validations to Gremium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GremienController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gremien as @gremien" do
      gremium = Gremium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gremien).should eq([gremium])
    end
  end

  describe "GET show" do
    it "assigns the requested gremium as @gremium" do
      gremium = Gremium.create! valid_attributes
      get :show, {:id => gremium.to_param}, valid_session
      assigns(:gremium).should eq(gremium)
    end
  end

  describe "GET new" do
    it "assigns a new gremium as @gremium" do
      get :new, {}, valid_session
      assigns(:gremium).should be_a_new(Gremium)
    end
  end

  describe "GET edit" do
    it "assigns the requested gremium as @gremium" do
      gremium = Gremium.create! valid_attributes
      get :edit, {:id => gremium.to_param}, valid_session
      assigns(:gremium).should eq(gremium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gremium" do
        expect {
          post :create, {:gremium => valid_attributes}, valid_session
        }.to change(Gremium, :count).by(1)
      end

      it "assigns a newly created gremium as @gremium" do
        post :create, {:gremium => valid_attributes}, valid_session
        assigns(:gremium).should be_a(Gremium)
        assigns(:gremium).should be_persisted
      end

      it "redirects to the created gremium" do
        post :create, {:gremium => valid_attributes}, valid_session
        response.should redirect_to(Gremium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gremium as @gremium" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gremium.any_instance.stub(:save).and_return(false)
        post :create, {:gremium => { "name" => "invalid value" }}, valid_session
        assigns(:gremium).should be_a_new(Gremium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gremium.any_instance.stub(:save).and_return(false)
        post :create, {:gremium => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gremium" do
        gremium = Gremium.create! valid_attributes
        # Assuming there are no other gremien in the database, this
        # specifies that the Gremium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gremium.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => gremium.to_param, :gremium => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested gremium as @gremium" do
        gremium = Gremium.create! valid_attributes
        put :update, {:id => gremium.to_param, :gremium => valid_attributes}, valid_session
        assigns(:gremium).should eq(gremium)
      end

      it "redirects to the gremium" do
        gremium = Gremium.create! valid_attributes
        put :update, {:id => gremium.to_param, :gremium => valid_attributes}, valid_session
        response.should redirect_to(gremium)
      end
    end

    describe "with invalid params" do
      it "assigns the gremium as @gremium" do
        gremium = Gremium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gremium.any_instance.stub(:save).and_return(false)
        put :update, {:id => gremium.to_param, :gremium => { "name" => "invalid value" }}, valid_session
        assigns(:gremium).should eq(gremium)
      end

      it "re-renders the 'edit' template" do
        gremium = Gremium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gremium.any_instance.stub(:save).and_return(false)
        put :update, {:id => gremium.to_param, :gremium => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gremium" do
      gremium = Gremium.create! valid_attributes
      expect {
        delete :destroy, {:id => gremium.to_param}, valid_session
      }.to change(Gremium, :count).by(-1)
    end

    it "redirects to the gremien list" do
      gremium = Gremium.create! valid_attributes
      delete :destroy, {:id => gremium.to_param}, valid_session
      response.should redirect_to(gremien_url)
    end
  end

end
