require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThemengruppenController do

  # This should return the minimal set of attributes required to create a valid
  # Themengruppe. As you add validations to Themengruppe, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThemengruppenController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all themengruppenn as @themengruppenn" do
      themengruppe = Themengruppe.create! valid_attributes
      get :index, {}, valid_session
      assigns(:themengruppen).should eq([themengruppe])
    end
  end

  describe "GET show" do
    it "assigns the requested themengruppe as @themengruppe" do
      themengruppe = Themengruppe.create! valid_attributes
      get :show, {:id => themengruppe.to_param}, valid_session
      assigns(:themengruppe).should eq(themengruppe)
    end
  end

  describe "GET new" do
    it "assigns a new themengruppe as @themengruppe" do
      get :new, {}, valid_session
      assigns(:themengruppe).should be_a_new(Themengruppe)
    end
  end

  describe "GET edit" do
    it "assigns the requested themengruppe as @themengruppe" do
      themengruppe = Themengruppe.create! valid_attributes
      get :edit, {:id => themengruppe.to_param}, valid_session
      assigns(:themengruppe).should eq(themengruppe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Themengruppe" do
        expect {
          post :create, {:themengruppe => valid_attributes}, valid_session
        }.to change(Themengruppe, :count).by(1)
      end

      it "assigns a newly created themengruppe as @themengruppe" do
        post :create, {:themengruppe => valid_attributes}, valid_session
        assigns(:themengruppe).should be_a(Themengruppe)
        assigns(:themengruppe).should be_persisted
      end

      it "redirects to the created themengruppe" do
        post :create, {:themengruppe => valid_attributes}, valid_session
        response.should redirect_to(Themengruppe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved themengruppe as @themengruppe" do
        # Trigger the behavior that occurs when invalid params are submitted
        Themengruppe.any_instance.stub(:save).and_return(false)
        post :create, {:themengruppe => { "title" => "invalid value" }}, valid_session
        assigns(:themengruppe).should be_a_new(Themengruppe)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Themengruppe.any_instance.stub(:save).and_return(false)
        post :create, {:themengruppe => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested themengruppe" do
        themengruppe = Themengruppe.create! valid_attributes
        # Assuming there are no other themengruppen in the database, this
        # specifies that the Themengruppe created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Themengruppe.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => themengruppe.to_param, :themengruppe => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested themengruppe as @themengruppe" do
        themengruppe = Themengruppe.create! valid_attributes
        put :update, {:id => themengruppe.to_param, :themengruppe => valid_attributes}, valid_session
        assigns(:themengruppe).should eq(themengruppe)
      end

      it "redirects to the themengruppe" do
        themengruppe = Themengruppe.create! valid_attributes
        put :update, {:id => themengruppe.to_param, :themengruppe => valid_attributes}, valid_session
        response.should redirect_to(themengruppe)
      end
    end

    describe "with invalid params" do
      it "assigns the themengruppe as @themengruppe" do
        themengruppe = Themengruppe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Themengruppe.any_instance.stub(:save).and_return(false)
        put :update, {:id => themengruppe.to_param, :themengruppe => { "title" => "invalid value" }}, valid_session
        assigns(:themengruppe).should eq(themengruppe)
      end

      it "re-renders the 'edit' template" do
        themengruppe = Themengruppe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Themengruppe.any_instance.stub(:save).and_return(false)
        put :update, {:id => themengruppe.to_param, :themengruppe => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested themengruppe" do
      themengruppe = Themengruppe.create! valid_attributes
      expect {
        delete :destroy, {:id => themengruppe.to_param}, valid_session
      }.to change(Themengruppe, :count).by(-1)
    end

    it "redirects to the themengruppen list" do
      themengruppe = Themengruppe.create! valid_attributes
      delete :destroy, {:id => themengruppe.to_param}, valid_session
      response.should redirect_to(themengruppen_url)
    end
  end

end
